- name: checks the facts
  hosts: local
  connection: local
  tasks:
  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when: ansible_os_family == 'Redhat' # use ansible while reffering the facts

  - name: install nginx if debian
    ansible.builtin.apt:
      name: nginx
      state: latest
      when: ansible_os_family == "Debian"